# Generated by Django 4.2.16 on 2026-03-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_transformationvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TransformationVideo',
        ),
    ]
